### PR TITLE
feat: added hamburger on mobile

### PR DESCRIPTION
**Pull request by devpanther**

### CODE REVIEW

**Comment by pavlovcik** [comment]
Thanks for the contribution. Unfortunately it didn't match the spec. I asked for you to copy the CSS+HTML structure from our dApp uad.ubq.fi which does not use any JavaScript. 

Please review the spec.

**Comment by devpanther** [comment]
@pavlovcik check now

**Comment by pavlovcik** [comment]
@devpanther its my mistake for merging this in without fully testing it but unfortunately this pull request broke mobile support ironically for "click to start"

More information is available here https://github.com/ubiquity/ubq.fi/pull/12

**Comment by devpanther** [comment]
It only happened on safari? @pavlovcik

**Comment by devpanther** [comment]
> It only happened on safari? @pavlovcik, because it was tested on mobile.. Just didn't check for safari's compatibility 

Just checked, it's only on safari.. Fixing

**Comment by devpanther** [comment]
> More information is available here https://github.com/ubiquity/ubq.fi/pull/12

Fixed

**Pull request merged**
